repos:
  # Check for inconsistent line endings & whitespacing
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
  # Run eslint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.19.0
    hooks:
      - id: eslint
        files: \.ts$  # only typescript files
        types: [ file ]
        args: [--fix]
